### DISCUSSION TITLE
Case convention for feature names

### DISCUSSION THREAD

**Discussion by dtolnay** [rust-lang-nursery/api-guidelines#101] [API Guidelines]
Are they kebab case or camel case? This needs to be documented under C-CASE.

```toml
[features]
extra-special = []
extra_special = []
```

I propose that the answer should be the same as the answer for crate names (#29). That way the implicit feature that enables an optional dependency follows the same case convention as every explicit feature.
