### ISSUE TITLE
Feature names cannot always be free of placeholder words

### ISSUE THREAD

**Issue by rushmorem** [rust-lang-nursery/api-guidelines#164]
The recommendation for [C-FEATURE] says:-

> Do not call the feature `use-std` or `with-std` or any creative name that is not `std`.

I like this naming convention. Unfortunately, it's not always possible to follow. For example, say I want to add optional support for `serde`, the obvious name for such a feature would be `serde`. However, if some of my types can be derived automatically, I would also want to optionally depend on `serde_derive`. Part of my manifest will then end up as follows:

```toml
[features]
serde = ["serde", "serde_derive"]

[dependencies]
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }
```

However, this is not possible since feature names must not conflict with other package names in the manifest. In such a case, I will either have to use a name like `with-serde` or come up with a creative name for my feature.

[C-FEATURE]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#feature-names-are-free-of-placeholder-words-c-feature

**Edit:** Had forgotten to insert a hyperlink
